// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvuugxjseavbxpxhfprb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dXVneGpzZWF2YnhweGhmcHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTE5NTYsImV4cCI6MjA3NDQ2Nzk1Nn0.D06Vczp3BjgH9BBQo3u14nD6AqLFCJpxdJv9xS_4Z7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});